export const INITIAL_SOURCES = [
  { name: "STAT News", url: "https://www.statnews.com/feed/", type: "rss", section: "healthtech", geo: "US" },
  { name: "Rock Health", url: "https://rockhealth.com/feed/", type: "rss", section: "healthtech", geo: "Global" },
  { name: "MedCity News", url: "https://medcitynews.com/feed/", type: "rss", section: "healthtech", geo: "US" },
  { name: "Fierce Healthcare", url: "https://www.fiercehealthcare.com/rss/xml", type: "rss", section: "healthtech", geo: "US" },
  { name: "Healthcare IT News", url: "https://www.healthcareitnews.com/rss.xml", type: "rss", section: "healthtech", geo: "Global" },
  { name: "ET Health", url: "https://health.economictimes.indiatimes.com/rss/topstories", type: "rss", section: "healthtech", geo: "India" },
  { name: "The Ken Health", url: "https://the-ken.com/feed/", type: "rss", section: "healthtech", geo: "India" },
  { name: "Becker's Finance", url: "https://www.beckershospitalreview.com/rss/finance.xml", type: "rss", section: "investing", geo: "US" },
  { name: "Fierce Biotech", url: "https://www.fiercebiotech.com/rss/xml", type: "rss", section: "investing", geo: "Global" },
  { name: "Health Affairs", url: "https://www.healthaffairs.org/rss/site_5/41.xml", type: "rss", section: "investing", geo: "US" },
  { name: "Mint Health", url: "https://www.livemint.com/rss/healthcare", type: "rss", section: "investing", geo: "India" },
  { name: "CB Insights Health", url: "https://www.cbinsights.com/research/feed/", type: "rss", section: "investing", geo: "Global" },
  { name: "Modern Healthcare", url: "https://www.modernhealthcare.com/section/rss", type: "rss", section: "operations", geo: "US" },
  { name: "Becker's Ops", url: "https://www.beckershospitalreview.com/rss/hospital-management-administration.xml", type: "rss", section: "operations", geo: "US" },
  { name: "Express Healthcare", url: "https://www.expresshealthcare.in/feed/", type: "rss", section: "operations", geo: "India" },
  { name: "ET Health Ops", url: "https://health.economictimes.indiatimes.com/rss/topstories", type: "rss", section: "operations", geo: "India" },
  { name: "Health Payer Intel", url: "https://healthpayerintelligence.com/feed/", type: "rss", section: "insurance", geo: "US" },
  { name: "KFF", url: "https://kff.org/feed/", type: "rss", section: "insurance", geo: "US" },
  { name: "Hindu BL Insurance", url: "https://www.thehindubusinessline.com/economy/insurance/feed", type: "rss", section: "insurance", geo: "India" },
]
